apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cdx

resources:
  - namespace.yaml
  - ../base
  - nodeport-service.yaml

images:
  - name: cdx-image
    newName: gcr.io/vvvrun/cdx
    newTag: latest
