name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v ./cmd/cdx

    - name: Test
      run: go test -v ./...

    - name: Test E2E
      run: |
        git config --global user.email "azu-robot@ghostintheshe.ll"
        git config --global user.name "azu-robot"
        CDX_CMD=$PWD/cdx ./hack/run-e2e.sh
