name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: go build -v ./cmd/cdx

    - name: Test
      run: go test -v ./...
    
    - name: Release
      run: |
        git config --global user.name 'azu-robot'
        git config --global user.email 'azu-robot@users.noreply.github.com'
        git remote set-url --push origin https://azunymous:$GITHUB_TOKEN@github.com/azunymous/cdx
        ./cdx tag release -n cdx --push
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
